In [1]:
import pandas as pd
import numpy as np

In [2]:
medium_res = pd.read_csv("medium_result.csv", index_col=False)
medium_res

programming    design   science  critical thinking   player   levels  \
0         46319.0   23565.0   16218.0              963.0   2532.0   6995.0   
1         23565.0  190644.0   51930.0             5215.0  10553.0  36442.0   
2         16218.0   51930.0  121132.0             4333.0   6213.0  21331.0   
3           963.0    5215.0    4333.0            31859.0   1451.0   5691.0   
4           116.0     633.0     275.0               18.0     53.0    121.0   
...           ...       ...       ...                ...      ...      ...   
6550          NaN       NaN       NaN                NaN      NaN      NaN   
6551          NaN       NaN       NaN                NaN      NaN      NaN   
6552          NaN       NaN       NaN                NaN      NaN      NaN   
6553          NaN       NaN       NaN                NaN      NaN      NaN   
6554          NaN       NaN       NaN                NaN      NaN      NaN   

      microsoft office  imaging systems    skill    rules  ...  \
0               4202.0             76.0   4056.0   2638.0  ...   
1              21057.0            341.0  16992.0  10121.0  ...   
2              11102.0            369.0  10644.0   6198.0  ...   
3               3747.0             28.0   3375.0   2673.0  ...   
4                166.0              4.0     56.0     46.0  ...   
...                ...              ...      ...      ...  ...   
6550               NaN              NaN      NaN      NaN  ...   
6551               NaN              NaN      NaN      NaN  ...   
6552               NaN              NaN      NaN      NaN  ...   
6553               NaN              NaN      NaN      NaN  ...   
6554               NaN              NaN      NaN      NaN  ...   

      spin processors  scoring machines  pentagon 2000sql  fabric machines  \
0                 NaN               NaN               NaN              NaN   
1                 1.0               NaN               NaN              NaN   
2                 NaN               NaN               NaN              NaN   
3                 NaN               NaN               NaN              NaN   
4                 NaN               NaN               NaN              NaN   
...               ...               ...               ...              ...   
6550              NaN               NaN               NaN              NaN   
6551              NaN               NaN               NaN              NaN   
6552              NaN               NaN               NaN              NaN   
6553              NaN               1.0               NaN              NaN   
6554              NaN               NaN               NaN              1.0   

      paper folding machines  gauge lines  recording thermometers  \
0                        NaN          NaN                     NaN   
1                        NaN          NaN                     NaN   
2                        NaN          NaN                     NaN   
3                        NaN          NaN                     NaN   
4                        NaN          NaN                     NaN   
...                      ...          ...                     ...   
6550                     NaN          NaN                     NaN   
6551                     NaN          NaN                     NaN   
6552                     NaN          NaN                     NaN   
6553                     NaN          NaN                     NaN   
6554                     NaN          NaN                     NaN   

      cutter grinders  stress testing software  tensionmeters  
0                 1.0                      NaN            NaN  
1                 NaN                      1.0            NaN  
2                 NaN                      NaN            NaN  
3                 NaN                      NaN            NaN  
4                 NaN                      NaN            NaN  
...               ...                      ...            ...  
6550              NaN                      NaN            NaN 

In [3]:
medium_res.fillna(0)

programming    design   science  critical thinking   player   levels  \
0         46319.0   23565.0   16218.0              963.0   2532.0   6995.0   
1         23565.0  190644.0   51930.0             5215.0  10553.0  36442.0   
2         16218.0   51930.0  121132.0             4333.0   6213.0  21331.0   
3           963.0    5215.0    4333.0            31859.0   1451.0   5691.0   
4           116.0     633.0     275.0               18.0     53.0    121.0   
...           ...       ...       ...                ...      ...      ...   
6550          0.0       0.0       0.0                0.0      0.0      0.0   
6551          0.0       0.0       0.0                0.0      0.0      0.0   
6552          0.0       0.0       0.0                0.0      0.0      0.0   
6553          0.0       0.0       0.0                0.0      0.0      0.0   
6554          0.0       0.0       0.0                0.0      0.0      0.0   

      microsoft office  imaging systems    skill    rules  ...  \
0               4202.0             76.0   4056.0   2638.0  ...   
1              21057.0            341.0  16992.0  10121.0  ...   
2              11102.0            369.0  10644.0   6198.0  ...   
3               3747.0             28.0   3375.0   2673.0  ...   
4                166.0              4.0     56.0     46.0  ...   
...                ...              ...      ...      ...  ...   
6550               0.0              0.0      0.0      0.0  ...   
6551               0.0              0.0      0.0      0.0  ...   
6552               0.0              0.0      0.0      0.0  ...   
6553               0.0              0.0      0.0      0.0  ...   
6554               0.0              0.0      0.0      0.0  ...   

      spin processors  scoring machines  pentagon 2000sql  fabric machines  \
0                 0.0               0.0               0.0              0.0   
1                 1.0               0.0               0.0              0.0   
2                 0.0               0.0               0.0              0.0   
3                 0.0               0.0               0.0              0.0   
4                 0.0               0.0               0.0              0.0   
...               ...               ...               ...              ...   
6550              0.0               0.0               0.0              0.0   
6551              0.0               0.0               0.0              0.0   
6552              0.0               0.0               0.0              0.0   
6553              0.0               1.0               0.0              0.0   
6554              0.0               0.0               0.0              1.0   

      paper folding machines  gauge lines  recording thermometers  \
0                        0.0          0.0                     0.0   
1                        0.0          0.0                     0.0   
2                        0.0          0.0                     0.0   
3                        0.0          0.0                     0.0   
4                        0.0          0.0                     0.0   
...                      ...          ...                     ...   
6550                     0.0          0.0                     0.0   
6551                     0.0          0.0                     0.0   
6552                     0.0          0.0                     0.0   
6553                     0.0          0.0                     0.0   
6554                     0.0          0.0                     0.0   

      cutter grinders  stress testing software  tensionmeters  
0                 1.0                      0.0            0.0  
1                 0.0                      1.0            0.0  
2                 0.0                      0.0            0.0  
3                 0.0                      0.0            0.0  
4                 0.0                      0.0            0.0  
...               ...                      ...            ...  
6550              0.0                      0.0            0.0 

In [4]:
res_array = np.array(medium_res.fillna(0))
res_array

array([[4.63190e+04, 2.35650e+04, 1.62180e+04, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.35650e+04, 1.90644e+05, 5.19300e+04, ..., 0.00000e+00,
        1.00000e+00, 0.00000e+00],
       [1.62180e+04, 5.19300e+04, 1.21132e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [5]:
medium_res.iloc[1].iloc[1]

190644.0

In [6]:
def type(x, index):
    print(index)

In [7]:
res_array

array([[4.63190e+04, 2.35650e+04, 1.62180e+04, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.35650e+04, 1.90644e+05, 5.19300e+04, ..., 0.00000e+00,
        1.00000e+00, 0.00000e+00],
       [1.62180e+04, 5.19300e+04, 1.21132e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [8]:
from sklearn.feature_extraction.text import TfidfTransformer  

In [9]:
tf = TfidfTransformer()

In [10]:
X_tfidf = tf.fit_transform(res_array).toarray()

In [11]:
np.fliplr(np.argsort(X_tfidf))

array([[   0,    1,    2, ..., 4261, 4262, 3277],
       [   1,    2,   34, ..., 4224, 4228, 6554],
       [   2,    1,   34, ..., 4201, 4202, 3277],
       ...,
       [6534, 6554, 2176, ..., 4373, 4374,    0],
       [6546, 6554, 2188, ..., 4373, 4374,    0],
       [6548, 6554, 2188, ..., 4373, 4374,    0]], dtype=int64)

In [12]:
X_tfidf

array([[8.08326059e-01, 3.02414442e-01, 2.38938856e-01, ...,
        6.18519239e-05, 0.00000000e+00, 0.00000000e+00],
       [1.35599965e-01, 8.06720240e-01, 2.52274025e-01, ...,
        0.00000000e+00, 2.09485168e-05, 0.00000000e+00],
       [1.29070690e-01, 3.03917940e-01, 8.13862997e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [15]:
from scipy.spatial.distance import cdist

In [16]:
def cos_sim(A, B):
    similarities = 1 - cdist(A, B, metric='cosine')
    return similarities

In [17]:
similarities = cos_sim(X_tfidf, X_tfidf)

In [18]:
similarities

array([[1.        , 0.62906916, 0.591618  , ..., 0.        , 0.        ,
        0.        ],
       [0.62906916, 1.        , 0.70780643, ..., 0.        , 0.        ,
        0.        ],
       [0.591618  , 0.70780643, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [19]:
medium_res.columns

Index(['programming', 'design', 'science', 'critical thinking', 'player',
       'levels', 'microsoft office', 'imaging systems', 'skill', 'rules',
       ...
       'spin processors', 'scoring machines', 'pentagon 2000sql',
       'fabric machines', 'paper folding machines', 'gauge lines',
       'recording thermometers', 'cutter grinders', 'stress testing software',
       'tensionmeters'],
      dtype='object', length=6555)

In [21]:
similar = pd.DataFrame(similarities, columns=medium_res.columns)

In [22]:
similar

programming    design   science  critical thinking    player    levels  \
0        1.000000  0.629069  0.591618           0.189034  0.261588  0.287784   
1        0.629069  1.000000  0.707806           0.272986  0.387306  0.415829   
2        0.591618  0.707806  1.000000           0.267301  0.311023  0.372064   
3        0.189034  0.272986  0.267301           1.000000  0.115031  0.213004   
4        0.261588  0.387306  0.311023           0.115031  1.000000  0.183933   
...           ...       ...       ...                ...       ...       ...   
6550     0.000000  0.000000  0.000000           0.000000  0.000000  0.000000   
6551     0.000000  0.000000  0.000000           0.000000  0.000000  0.000000   
6552     0.000000  0.000000  0.000000           0.000000  0.000000  0.000000   
6553     0.000000  0.000000  0.000000           0.000000  0.000000  0.000000   
6554     0.000000  0.000000  0.000000           0.000000  0.000000  0.000000   

      microsoft office  imaging systems     skill     rules  ...  \
0             0.386635         0.497251  0.276587  0.460854  ...   
1             0.511966         0.619263  0.327616  0.574691  ...   
2             0.483811         0.543626  0.317536  0.534094  ...   
3             0.316370         0.203654  0.135750  0.232487  ...   
4             0.205152         0.232840  0.161511  0.236290  ...   
...                ...              ...       ...       ...  ...   
6550          0.000000         0.000000  0.000000  0.000000  ...   
6551          0.000000         0.000000  0.000000  0.000000  ...   
6552          0.000000         0.000000  0.000000  0.000000  ...   
6553          0.000000         0.000000  0.000000  0.000000  ...   
6554          0.000000         0.000000  0.000000  0.000000  ...   

      spin processors  scoring machines  pentagon 2000sql  fabric machines  \
0                 0.0               0.0               0.0              0.0   
1                 0.0               0.0               0.0              0.0   
2                 0.0               0.0               0.0              0.0   
3                 0.0               0.0               0.0              0.0   
4                 0.0               0.0               0.0              0.0   
...               ...               ...               ...              ...   
6550              0.0               0.0               0.0              0.0   
6551              0.0               0.0               0.0              0.0   
6552              0.0               0.0               0.0              0.0   
6553              0.0               0.0               0.0              0.0   
6554              0.0               0.0               0.0              0.0   

      paper folding machines  gauge lines  recording thermometers  \
0                        0.0          0.0                     0.0   
1                        0.0          0.0                     0.0   
2                        0.0          0.0                     0.0   
3                        0.0          0.0                     0.0   
4                        0.0          0.0                     0.0   
...                      ...          ...                     ...   
6550                     0.0          1.0                     0.0   
6551                     0.0          0.0                     1.0   
6552                     0.0          0.0                     0.0   
6553                     0.0          0.0                     0.0   
6554                     0.0          0.0                     0.0   

      cutter grinders  stress testing software  tensionmeters  
0                 0.0                      0.0            0.0  
1                 0.0                      0.0            0.0  
2                 0.0                      0.0            0.0  
3                 0.0                      0.0            0.0  
4                 0.0                      0.0            0.0  
...               ...                      ...            ...  
6550          

In [24]:
similar.to_csv("similar.csv", index=False)